package tui

import (
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/gdamore/tcell/v2"
	"github.com/rivo/tview"
	"github.com/svg153/reclaimit/internal/scanner"
)

func sampleReport(t *testing.T) Report {
	t.Helper()
	root := t.TempDir()
	modified := time.Date(2026, 8, 14, 8, 0, 0, 0, time.UTC)
	return scanner.Report{
		Root: root,
		Candidates: []scanner.Candidate{
			{
				Path: filepath.Join(root, "repo-b", "node_modules"), Bytes: 20,
				CategoryKey: "node-modules", Description: "reinstall dependencies",
				ModifiedAt: modified, IsDir: true,
			},
			{
				Path: filepath.Join(root, "repo-a", "cache.pyc"), Bytes: 10,
				CategoryKey: "python-bytecode", Description: "regenerated bytecode",
				ModifiedAt: modified.Add(time.Hour), IsDir: false,
			},
		},
	}
}

func TestBuildSelectionTreeBuildsAndSortsContext(t *testing.T) {
	report := sampleReport(t)
	roots := buildSelectionTree(report)
	if len(roots) != 2 {
		t.Fatalf("expected two roots, got %#v", roots)
	}
	if roots[0].label != "repo-b" || roots[0].bytes != 20 || roots[0].candidateCount != 1 {
		t.Fatalf("unexpected first root: %#v", roots[0])
	}
	leaf := roots[0].children[0]
	if leaf.kind != nodeCandidate || leaf.cand == nil || leaf.parent != roots[0] {
		t.Fatalf("unexpected candidate leaf: %#v", leaf)
	}
	if got := buildSelectionTree(Report{Root: report.Root}); len(got) != 0 {
		t.Fatalf("empty report produced roots: %#v", got)
	}
}

func TestBuildSelectionTreeHandlesCandidateAtRoot(t *testing.T) {
	root := t.TempDir()
	roots := buildSelectionTree(Report{Root: root, Candidates: []Candidate{{
		Path: root, Bytes: 3, CategoryKey: "generic-cache", IsDir: true,
	}}})
	if len(roots) != 1 || roots[0].kind != nodeCandidate || roots[0].cand == nil {
		t.Fatalf("unexpected root candidate: %#v", roots)
	}
}

func TestTreeNodeRenderingAndRefresh(t *testing.T) {
	report := sampleReport(t)
	model := buildSelectionTree(report)[0]
	model.label = "  repo-b  "
	treeNode := buildTreeNode(model)
	if treeNode.GetReference() != model || len(treeNode.GetChildren()) != 1 {
		t.Fatalf("tree node does not preserve model: %#v", treeNode)
	}
	if model.label != "repo-b" {
		t.Fatalf("nodeTreeRef did not trim label: %q", model.label)
	}

	before := treeNode.GetText()
	toggleSelection(model, false)
	refreshTreeNodes(treeNode)
	after := treeNode.GetText()
	if before == after || !strings.Contains(after, "○") {
		t.Fatalf("tree refresh did not update selection: before=%q after=%q", before, after)
	}
}

func TestRenderNodeLabelCoversFolderDirectoryAndFile(t *testing.T) {
	folder := makeFolder("/root/folder", makeLeaf("/root/folder/file", 1, true))
	folder.bytes, folder.candidateCount = 1024, 1
	if got := renderNodeLabel(folder); !strings.Contains(got, "📁") || !strings.Contains(got, "1.0 KiB") {
		t.Fatalf("unexpected folder label: %q", got)
	}

	dirCandidate := makeLeaf("/root/node_modules", 2048, true)
	dirCandidate.cand = &Candidate{CategoryKey: "node-modules", IsDir: true}
	if got := renderNodeLabel(dirCandidate); !strings.Contains(got, "🧹") || !strings.Contains(got, "node-modules") {
		t.Fatalf("unexpected directory label: %q", got)
	}

	fileCandidate := makeLeaf("/root/cache.pyc", 10, true)
	fileCandidate.cand = &Candidate{CategoryKey: "python-bytecode", IsDir: false}
	if got := renderNodeLabel(fileCandidate); !strings.Contains(got, "📄") {
		t.Fatalf("unexpected file label: %q", got)
	}
}

func TestFindOrCreateChildAndSortTree(t *testing.T) {
	parent := makeFolder("/root")
	file := findOrCreateChild(parent, "z.pyc", "/root/z.pyc", true)
	folder := findOrCreateChild(parent, "a", "/root/a", false)
	same := findOrCreateChild(parent, "z.pyc", "/root/z.pyc", true)
	if same != file || len(parent.children) != 2 || folder.kind != nodeFolder {
		t.Fatalf("findOrCreateChild failed: %#v", parent.children)
	}
	file.bytes = 100
	folder.bytes = 1
	sortTree(parent)
	if parent.children[0] != folder {
		t.Fatalf("folders should sort before candidates: %#v", parent.children)
	}
}

func TestDescribeNodeAndColors(t *testing.T) {
	modified := time.Date(2026, 8, 14, 8, 30, 0, 0, time.UTC)
	selected := makeLeaf("/root/cache.pyc", 1024, true)
	selected.modifiedAt = modified
	selected.cand = &Candidate{
		CategoryKey: "python-bytecode", Description: "regenerated", IsDir: false,
	}
	if got := describeNode(selected); !strings.Contains(got, "file") || !strings.Contains(got, "regenerated") {
		t.Fatalf("unexpected file description: %q", got)
	}
	if nodeColor(selected) != tcell.ColorMediumPurple {
		t.Fatalf("unexpected selected file color")
	}
	selected.selected = false
	if nodeColor(selected) != tcell.ColorSlateGray {
		t.Fatalf("unexpected unselected file color")
	}

	dir := makeLeaf("/root/node_modules", 10, true)
	dir.cand = &Candidate{CategoryKey: "node-modules", IsDir: true}
	if !strings.Contains(describeNode(dir), "directory") || nodeColor(dir) != tcell.ColorTurquoise {
		t.Fatalf("unexpected directory candidate presentation")
	}

	folder := makeFolder("/root/repo", makeLeaf("/root/repo/a", 1, true), makeLeaf("/root/repo/b", 1, false))
	folder.bytes, folder.candidateCount, folder.modifiedAt = 2, 2, modified
	if got := describeNode(folder); !strings.Contains(got, "Context folder") || !strings.Contains(got, "partially selected") {
		t.Fatalf("unexpected folder description: %q", got)
	}
	if nodeColor(folder) != tcell.ColorLightSkyBlue {
		t.Fatalf("unexpected partial folder color")
	}
	toggleSelection(folder, true)
	if nodeColor(folder) != tcell.ColorDeepSkyBlue {
		t.Fatalf("unexpected selected folder color")
	}
	toggleSelection(folder, false)
	if nodeColor(folder) != tcell.ColorSlateGray {
		t.Fatalf("unexpected disabled folder color")
	}
}

func TestTreeNavigationHelpers(t *testing.T) {
	root := tview.NewTreeNode("root")
	child := tview.NewTreeNode("child")
	grandchild := tview.NewTreeNode("grandchild")
	child.AddChild(grandchild)
	root.AddChild(child)
	if firstSelectableTreeNode(root) != child {
		t.Fatal("expected first child")
	}
	if firstSelectableTreeNode(tview.NewTreeNode("empty")).GetText() != "empty" {
		t.Fatal("empty root should be returned")
	}
	if findParentTreeNode(root, grandchild) != child || findParentTreeNode(root, child) != root {
		t.Fatal("parent lookup failed")
	}
	if findParentTreeNode(nil, child) != nil || findParentTreeNode(root, nil) != nil {
		t.Fatal("nil parent lookup should return nil")
	}
	if findParentTreeNode(root, tview.NewTreeNode("missing")) != nil {
		t.Fatal("missing node should not have a parent")
	}
}

func TestRunWithSimulationScreenSavesSelection(t *testing.T) {
	report := sampleReport(t)
	events := []*tcell.EventKey{
		tcell.NewEventKey(tcell.KeyRight, 0, tcell.ModNone),
		tcell.NewEventKey(tcell.KeyLeft, 0, tcell.ModNone),
		tcell.NewEventKey(tcell.KeyEnter, 0, tcell.ModNone),
		tcell.NewEventKey(tcell.KeyRune, ' ', tcell.ModNone),
		tcell.NewEventKey(tcell.KeyRune, 'a', tcell.ModNone),
		tcell.NewEventKey(tcell.KeyRune, 'j', tcell.ModNone),
		tcell.NewEventKey(tcell.KeyRune, 'k', tcell.ModNone),
		tcell.NewEventKey(tcell.KeyRune, 'l', tcell.ModNone),
		tcell.NewEventKey(tcell.KeyRune, 'h', tcell.ModNone),
		tcell.NewEventKey(tcell.KeyRune, 'q', tcell.ModNone),
	}
	selection := runSimulation(t, report, events...)
	if !selection.Saved {
		t.Fatalf("q should save the selection: %#v", selection)
	}
}

func TestRunWithSimulationScreenCancels(t *testing.T) {
	selection := runSimulation(t, sampleReport(t), tcell.NewEventKey(tcell.KeyEscape, 0, tcell.ModNone))
	if selection.Saved {
		t.Fatalf("escape should not save: %#v", selection)
	}
}

func runSimulation(t *testing.T, report Report, events ...*tcell.EventKey) Selection {
	t.Helper()
	screen := tcell.NewSimulationScreen("UTF-8")
	if err := screen.Init(); err != nil {
		t.Fatalf("init simulation screen: %v", err)
	}
	screen.SetSize(120, 40)
	t.Cleanup(screen.Fini)
	app := tview.NewApplication().SetScreen(screen)
	type runResult struct {
		selection Selection
		err       error
	}
	result := make(chan runResult, 1)
	go func() {
		selection, err := runWithApplication(report, app)
		result <- runResult{selection: selection, err: err}
	}()

	ready := make(chan struct{})
	app.QueueUpdateDraw(func() {
		close(ready)
	})
	select {
	case <-ready:
	case <-time.After(2 * time.Second):
		app.Stop()
		t.Fatal("TUI did not become ready")
	}
	for _, event := range events {
		if err := screen.PostEvent(event); err != nil {
			t.Fatalf("post event: %v", err)
		}
	}
	select {
	case got := <-result:
		if got.err != nil {
			t.Fatalf("run TUI: %v", got.err)
		}
		return got.selection
	case <-time.After(2 * time.Second):
		app.Stop()
		t.Fatal("TUI did not stop after input")
		return Selection{}
	}
}
